# Generated by Django 6.0 on 2026-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employement_type', models.CharField(choices=[('full_time', 'Full_Time'), ('part_time', 'Part_Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=25)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('applicants', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.IntegerField(default=0)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20)),
                ('job_type', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
