# Generated by Django 6.0 on 2026-02-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
    ]
