# Generated by Django 6.0 on 2026-01-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_is_staff_and_more'),
        ('users', '0007_remove_user_slug'),
    ]

    operations = [
    ]
